package:
  name: ibpy2
  version: "0.8.0"

source:
  fn: IbPy2-0.8.0.tar.gz
  url: https://pypi.python.org/packages/63/75/98a31bebdbd90ef6ca1769d690bbc52c4e2557ea19dcce150c4c8147e02e/IbPy2-0.8.0.tar.gz
  md5: 2275d9acbce7b065ee42b0b7872902dd
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ibpy2 = ibpy2:main
    #
    # Would create an entry point called ibpy2 that calls ibpy2.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - ib
    - ib.ext
    - ib.lib
    - ib.opt
    - ib.sym

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/blampe/IbPy
  license: BSD License
  summary: 'IbPy - Interactive Brokers Python API'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
